apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: dynatrace-keda-auth
spec:
  secretTargetRef:
    - key: apiKey
      name: keda-metric-api-secret-v000
      parameter: apiKey
----------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: keda-metric-api-secret
  namespace: test-ns
stringData:
  apiKey: >-
    Api-Token
    dynatrace api token
-----------------------------------------------------------
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: demo-app
  name: demoapp--multipletrigger
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          policies:
            - periodSeconds: 30
              type: Pods
              value: 1
          stabilizationWindowSeconds: 50
        scaleUp:
          policies:
            - periodSeconds: 10
              type: Pods
              value: 1
          stabilizationWindowSeconds: 10
  cooldownPeriod: 600
  fallback:
    failureThreshold: 2
    replicas: 1
  maxReplicaCount: 2
  minReplicaCount: 2
  scaleTargetRef:
    name: es-auth-authentication-v1-svc
  triggers:
    - authenticationRef:
        name: dynatrace-keda-auth
      metadata:
        authMode: apiKey
        keyParamName: Authorization
        method: header
        targetValue: '10'
        url: >-
        Dynatrace tenant url
      valueLocation: result.0.data.0.values.0
      type: metrics-api
    - metadata:
        value: '80'
      metricType: Utilization
      type: memory
    - metadata:
        value: '80'
      metricType: Utilization
      type: cpu

